name: Sync staging s3 with production state

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'type "staging" to confirm'
        required: true

jobs:
  sync:
    name: Sync staging s3 with production state
    if: ${{ github.event.inputs.bucket == 'staging' }}
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Auth aws
        #run: something required to auth

      - name: Run AWS sync prod to staging
        #run: make ci/sync-s3
